(() => {
const POS=["QB","RB","WR","TE","K","DST"],clean=s=>(s||"").replace(/\s+/g," ").trim();let timer;
function tournament(text){const m=text.match(/Battle Royale\s*-?\s*Week\s*\d+/i);if(m)return m[0].replace(/royale/i,"Royale");const heads=[...document.querySelectorAll("h1,h2,h3,[role=heading]")].map(x=>clean(x.textContent)).filter(t=>t.length>3&&t.length<100);return heads.find(t=>/battle royale|draft|playbook|bomb/i.test(t))||"Unknown Contest"}
function players(){const seen=new Map();for(const el of document.querySelectorAll("body *")){const t=clean(el.textContent);if(!t||t.length>100)continue;const p=POS.find(x=>new RegExp(`(^|\\s)${x}(\\s|$)`).test(t));if(!p)continue;const bits=t.split(/\n| · | - /).map(clean).filter(Boolean),n=bits.find(x=>x.length>=4&&x.length<=35&&!POS.includes(x)&&/[A-Za-z]/.test(x));if(n)seen.set(n,{name:n,position:p})}return [...seen.values()].slice(0,20)}
function complete(text,ps){return ps.length>=5&&/(completed|final roster|draft results|results)/i.test(text)}
async function save(){const text=clean(document.body?.innerText);if(!text)return;const ps=players();if(!complete(text,ps))return;const contest=tournament(text);const draftId=location.pathname.match(/drafts?\/([^/?#]+)/i)?.[1]||null;chrome.runtime.sendMessage({type:"NUKE_SAVE_DRAFT",draft:{draftId,sport:"NFL",format:"Daily Draft",contest,players:ps,sourceUrl:location.href,capturedAt:new Date().toISOString()}})}
async function exposures(){const {drafts=[]}=await chrome.storage.local.get({drafts:[]});const text=clean(document.body?.innerText),contest=tournament(text);if(contest==="Unknown Contest")return null;const ds=drafts.filter(d=>d.contest===contest),m=new Map();ds.forEach(d=>[...new Set((d.players||[]).map(p=>p.name))].forEach(n=>m.set(n,(m.get(n)||0)+1)));return {contest,total:ds.length,map:m}}
function addBadges(ex){if(!ex||!ex.total)return;document.querySelectorAll("[data-nuke-exposure]").forEach(x=>x.remove());for(const [name,count] of ex.map){const candidates=[...document.querySelectorAll("body *")].filter(el=>{const t=clean(el.textContent);return t===name||t.startsWith(name+" ")||t.includes(name)});const target=candidates.find(el=>el.children.length<8&&el.getBoundingClientRect().height>0);if(!target)continue;const badge=document.createElement("span");badge.dataset.nukeExposure="1";badge.className="nuke-exposure-badge";badge.textContent=`NUKE ${Math.round(count/ex.total*100)}% (${count}/${ex.total})`;badge.title=`${name}: ${count} of ${ex.total} completed ${ex.contest} drafts`;target.appendChild(badge)}}
async function scan(){await save();addBadges(await exposures())}
const obs=new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(scan,700)});obs.observe(document.documentElement,{childList:true,subtree:true});chrome.storage.onChanged.addListener(()=>{clearTimeout(timer);timer=setTimeout(scan,300)});setTimeout(scan,1500);
})();