let activeTab="players",allDrafts=[];const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\\\"":"&quot;","'":"&#039;"}[c]));
function status(t,s="working"){$("syncText").textContent=t;$("syncStatus").className="sync "+s}
function sports(){return ["ALL",...[...new Set(allDrafts.map(d=>d.sport).filter(Boolean))].sort()]}
function buildFilters(prefSport,prefContest){const sport=prefSport||$("sport").value||"ALL";$("sport").innerHTML=sports().map(x=>`<option ${x===sport?"selected":""}>${esc(x==="ALL"?"ALL SPORTS":x)}</option>`).join("");const valid=allDrafts.filter(d=>sport==="ALL"||d.sport===sport);const contests=["ALL",...[...new Set(valid.map(d=>d.contest).filter(Boolean))].sort()];const contest=contests.includes(prefContest)?prefContest:(contests.includes($("contest").value)?$("contest").value:"ALL");$("contest").innerHTML=contests.map(x=>`<option ${x===contest?"selected":""}>${esc(x==="ALL"?"ALL TOURNAMENTS":x)}</option>`).join("")}
async function persist(){await chrome.storage.local.set({exposureScope:{sport:$("sport").value||"ALL",contest:$("contest").value||"ALL"},lastSelectedContest:$("contest").value||"ALL"})}
function filtered(){const s=$("sport").value,c=$("contest").value;return allDrafts.filter(d=>(s==="ALL"||d.sport===s)&&(c==="ALL"||d.contest===c))}
let playerUniverse={};
const norm=s=>String(s||"").trim().toLowerCase().replace(/[’]/g,"'").replace(/[^a-z0-9'. -]/g,"").replace(/\s+/g," ");
const tokens=s=>norm(s).split(" ").filter(Boolean);
const aliases=s=>{const a=tokens(s);if(!a.length)return[];const out=[norm(s),a.at(-1)];if(a.length>1)out.push(a.slice(-2).join(" "));if(/^(ii|iii|iv|jr|sr)$/.test(a.at(-1))&&a.length>1)out.push(a.at(-2));return[...new Set(out)]};
function fullName(raw){
 const key=norm(raw);if(!key)return String(raw||"");
 if(playerUniverse[key])return playerUniverse[key].name||String(raw);
 const candidates=Object.entries(playerUniverse).filter(([full])=>aliases(full).includes(key));
 return candidates.length===1?(candidates[0][1].name||candidates[0][0]):String(raw);
}
function playerStats(ds){const m=new Map();ds.forEach(d=>{const seen=new Set();(d.players||[]).forEach(p=>{const name=fullName(p.name),key=norm(name);if(!key||seen.has(key))return;seen.add(key);const cur=m.get(key)||{name,count:0};cur.name=name;cur.count++;m.set(key,cur)})});return [...m.values()].map(x=>({...x,pct:ds.length?100*x.count/ds.length:0})).sort((a,b)=>b.pct-a.pct||a.name.localeCompare(b.name))}
function comboStats(ds){const m=new Map();ds.forEach(d=>{const n=[...new Set((d.players||[]).map(p=>p.name).filter(Boolean))].sort();for(let i=0;i<n.length;i++)for(let j=i+1;j<n.length;j++){const k=n[i]+" + "+n[j];m.set(k,(m.get(k)||0)+1)}});return [...m].map(([name,count])=>({name,count,pct:ds.length?100*count/ds.length:0})).sort((a,b)=>b.pct-a.pct||a.name.localeCompare(b.name))}
function empty(){return '<div class="empty">No completed drafts captured for this scope yet.</div>'}
function render(){const ds=filtered(),ps=playerStats(ds),cs=comboStats(ds);$("draftCount").textContent=ds.length;$("playerCount").textContent=ps.length;$("comboCount").textContent=cs.length;const q=$("search").value.toLowerCase();if(activeTab==="drafts"){$("view").innerHTML=ds.length?ds.map(d=>`<div class="row"><div><b>${esc(d.contest)}</b><br><small>${esc((d.players||[]).map(p=>p.name).join(", "))}</small></div><div></div><div class="num">${new Date(d.capturedAt).toLocaleDateString()}</div></div>`).join(""):empty();return}const rows=(activeTab==="players"?ps:cs).filter(x=>x.name.toLowerCase().includes(q));$("view").innerHTML=rows.length?rows.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="bar"><i style="width:${Math.min(100,x.pct)}%"></i></div></div><div class="num">${x.count}/${ds.length}</div><div class="pct">${x.pct.toFixed(1)}%</div></div>`).join(""):empty()}
async function load(){const d=await chrome.storage.local.get({drafts:[],exposureScope:{sport:"ALL",contest:"ALL"},lastSelectedContest:"ALL",playerUniverse:{}});allDrafts=d.drafts||[];playerUniverse=d.playerUniverse||{};const scope=d.exposureScope||{sport:"ALL",contest:d.lastSelectedContest||"ALL"};buildFilters(scope.sport,scope.contest);render();status(allDrafts.length?`Ready · ${allDrafts.length} drafts tracked`:"No drafts captured yet","ok");try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(tab?.id)await chrome.tabs.sendMessage(tab.id,{type:"NUKE_FORCE_SCAN"})}catch{} }
$("sport").addEventListener("change",async()=>{buildFilters($("sport").value,"ALL");await persist();render()});$("contest").addEventListener("change",async()=>{await persist();render()});$("search").addEventListener("input",render);$("refresh").addEventListener("click",load);document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeTab=b.dataset.tab;render()}));chrome.storage.onChanged.addListener(async(ch,a)=>{if(a!=="local")return;if(ch.drafts){allDrafts=ch.drafts.newValue||[];const d=await chrome.storage.local.get({exposureScope:{sport:"ALL",contest:"ALL"}});buildFilters(d.exposureScope.sport,d.exposureScope.contest);render();status(`Ready · ${allDrafts.length} drafts tracked`,"ok")}});load();