let activeTab="players",allDrafts=[];const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function status(text,state="working"){const el=$("syncStatus");$("syncText").textContent=text;el.className="sync "+state}
async function load(){status("Loading saved exposure…","working");const d=await chrome.storage.local.get({drafts:[]});allDrafts=d.drafts||[];buildContests();render();status(allDrafts.length?`Ready · ${allDrafts.length} drafts tracked`:"No drafts captured yet","ok");try{const tabs=await chrome.tabs.query({active:true,currentWindow:true});if(tabs[0]?.id)chrome.tabs.sendMessage(tabs[0].id,{type:"NUKE_FORCE_SCAN"}).then(async()=>{const x=await chrome.storage.local.get({drafts:[]});allDrafts=x.drafts||[];buildContests();render();status(`Ready · ${allDrafts.length} drafts tracked`,"ok")}).catch(()=>{})}catch(e){}}
async function persistContest(){const v=$("contestSelect").value;if(v&&v!=="ALL TOURNAMENTS")await chrome.storage.local.set({lastSelectedContest:v})}\nfunction buildContests(){const cur=$("contest").value||"ALL";const xs=[...new Set(allDrafts.map(d=>d.contest).filter(x=>x&&x!=="Unknown Contest"))].sort();$("contest").innerHTML=["ALL",...xs].map(x=>`<option ${x===cur?"selected":""}>${esc(x==="ALL"?"ALL TOURNAMENTS":x)}</option>`).join("")}
function filtered(){const c=$("contest").value;return allDrafts.filter(d=>c==="ALL"||d.contest===c)}
function playerStats(ds){const m=new Map();ds.forEach(d=>[...new Set((d.players||[]).map(p=>p.name))].forEach(n=>m.set(n,(m.get(n)||0)+1)));return [...m].map(([name,count])=>({name,count,pct:ds.length?count/ds.length*100:0})).sort((a,b)=>b.pct-a.pct||a.name.localeCompare(b.name))}
function comboStats(ds){const m=new Map();ds.forEach(d=>{const n=[...new Set((d.players||[]).map(p=>p.name))].sort();for(let i=0;i<n.length;i++)for(let j=i+1;j<n.length;j++){const k=n[i]+" + "+n[j];m.set(k,(m.get(k)||0)+1)}});return [...m].map(([name,count])=>({name,count,pct:ds.length?count/ds.length*100:0})).sort((a,b)=>b.pct-a.pct||a.name.localeCompare(b.name))}
function render(){const ds=filtered(),ps=playerStats(ds),cs=comboStats(ds);$("draftCount").textContent=ds.length;$("playerCount").textContent=ps.length;$("comboCount").textContent=cs.length;const q=$("search").value.toLowerCase();if(activeTab==="drafts"){$("view").innerHTML=ds.length?ds.map(d=>`<div class="row"><div><b>${esc(d.contest)}</b><br><small>${esc((d.players||[]).map(p=>p.name).join(", "))}</small></div><div></div><div class="num">${new Date(d.capturedAt).toLocaleDateString()}</div></div>`).join(""):empty();return}const rows=(activeTab==="players"?ps:cs).filter(x=>x.name.toLowerCase().includes(q));$("view").innerHTML=rows.length?rows.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="bar"><i style="width:${Math.min(100,x.pct)}%"></i></div></div><div class="num">${x.count}/${ds.length}</div><div class="pct">${x.pct.toFixed(1)}%</div></div>`).join(""):empty()}
function empty(){return '<div class="empty">No completed drafts captured for this tournament yet.<br>Open Underdog and your exposure will populate as drafts are captured.</div>'}
$("contest").addEventListener("change",render);$("search").addEventListener("input",render);$("refresh").addEventListener("click",load);document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeTab=b.dataset.tab;render()}));chrome.storage.onChanged.addListener(async changes=>{if(!changes.drafts)return;allDrafts=changes.drafts.newValue||[];buildContests();render();status(`Ready · ${allDrafts.length} drafts tracked`,"ok")});load();