let activeTab="players",allDrafts=[];const $=id=>document.getElementById(id);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
function status(t,s="ok"){$("syncText").textContent=t;$("syncStatus").className="sync "+s}
function sports(){return [...new Set(allDrafts.map(d=>d.sport||"UNKNOWN"))].sort()}
function buildFilters(prefSport,prefContest){const oldS=prefSport||$("sport").value||"ALL";$("sport").innerHTML=["ALL",...sports()].map(x=>`<option value="${esc(x)}" ${x===oldS?"selected":""}>${esc(x==="ALL"?"ALL SPORTS":x)}</option>`).join("");const s=$("sport").value;const cs=[...new Set(allDrafts.filter(d=>s==="ALL"||(d.sport||"UNKNOWN")===s).map(d=>d.contest).filter(Boolean))].sort();const oldC=prefContest||$("contest").value||"ALL";$("contest").innerHTML=["ALL",...cs].map(x=>`<option value="${esc(x)}" ${x===oldC?"selected":""}>${esc(x==="ALL"?"ALL TOURNAMENTS":x)}</option>`).join("")}
function filtered(){const s=$("sport").value,c=$("contest").value;return allDrafts.filter(d=>(s==="ALL"||(d.sport||"UNKNOWN")===s)&&(c==="ALL"||d.contest===c))}
function playerStats(ds){const m=new Map();ds.forEach(d=>[...new Set((d.players||[]).map(p=>p.name))].forEach(n=>m.set(n,(m.get(n)||0)+1)));return [...m].map(([name,count])=>({name,count,pct:ds.length?count/ds.length*100:0})).sort((a,b)=>b.pct-a.pct||a.name.localeCompare(b.name))}
function comboStats(ds){const m=new Map();ds.forEach(d=>{const n=[...new Set((d.players||[]).map(p=>p.name))].sort();for(let i=0;i<n.length;i++)for(let j=i+1;j<n.length;j++){const k=n[i]+" + "+n[j];m.set(k,(m.get(k)||0)+1)}});return [...m].map(([name,count])=>({name,count,pct:ds.length?count/ds.length*100:0})).sort((a,b)=>b.pct-a.pct||a.name.localeCompare(b.name))}
function empty(){return '<div class="empty">No completed drafts captured for this scope yet.</div>'}
function render(){const ds=filtered(),ps=playerStats(ds),cs=comboStats(ds);$("draftCount").textContent=ds.length;$("playerCount").textContent=ps.length;$("comboCount").textContent=cs.length;const q=$("search").value.toLowerCase();if(activeTab==="drafts"){$("view").innerHTML=ds.length?ds.map(d=>`<div class="row"><div><b>${esc(d.sport||"")} · ${esc(d.contest||"")}</b><br><small>${esc((d.players||[]).map(p=>p.name).join(", "))}</small></div><div></div><div class="num">${new Date(d.capturedAt).toLocaleDateString()}</div></div>`).join(""):empty();return}const rows=(activeTab==="players"?ps:cs).filter(x=>x.name.toLowerCase().includes(q));$("view").innerHTML=rows.length?rows.map(x=>`<div class="row"><div><b>${esc(x.name)}</b><div class="bar"><i style="width:${Math.min(100,x.pct)}%"></i></div></div><div class="num">${x.count}/${ds.length}</div><div class="pct">${x.pct.toFixed(1)}%</div></div>`).join(""):empty()}
async function persist(){await chrome.storage.local.set({lastSelectedSport:$("sport").value||"ALL",lastSelectedContest:$("contest").value||"ALL"})}
async function load(){const d=await chrome.storage.local.get({drafts:[],lastSelectedSport:"ALL",lastSelectedContest:"ALL"});allDrafts=d.drafts||[];buildFilters(d.lastSelectedSport,d.lastSelectedContest);render();status(allDrafts.length?`Ready · ${allDrafts.length} drafts tracked`:"No drafts captured yet");try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(tab?.id)chrome.tabs.sendMessage(tab.id,{type:"NUKE_FORCE_SCAN"}).catch(()=>{})}catch(e){}}
$("sport").addEventListener("change",async()=>{buildFilters(null,"ALL");await persist();render()});$("contest").addEventListener("change",async()=>{await persist();render()});$("search").addEventListener("input",render);$("refresh").addEventListener("click",load);document.querySelectorAll(".tab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");activeTab=b.dataset.tab;render()}));chrome.storage.onChanged.addListener(ch=>{if(ch.drafts){allDrafts=ch.drafts.newValue||[];buildFilters();render();status(`Ready · ${allDrafts.length} drafts tracked`)}});load();